version: '3.8'  # Specify the version of Docker Compose

services:
  backend:  # Backend service for Flask
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the backend
    volumes:
      - ./backend:/app  # Mount backend directory
    ports:
      - "5000:5000"  # Map port 5000 on host to port 5000 in container
    environment:
      - FLASK_ENV=development  # Set Flask environment to development
      - FLASK_APP=app.py  # Specify your main Flask application file

  frontend:  # Frontend service for React
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile  # Specify the Dockerfile for the frontend
    volumes:
      - ./frontend:/app  # Mount frontend directory
    ports:
      - "8080:8080"  # Map port 3000 on host to port 3000 in container

